<a href="https://colab.research.google.com/github/KAyush16/PyLibra/blob/main/basics_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics Of Numpy: Inserting, and chuturputur


In [ ]:
import numpy as np

a = np.array([1,3,4,67,8])
print(a)

[ 1  3  4 67  8]


In [ ]:
# 2d array and 3 d array
b = np.array([[1,2,4], [ 4,6,8]],dtype=float)

print (b)
print()
c= np.array([[[1,2],[2,4]],[[4,8],[7,9]]])
print(c)

[[1. 2. 4.]
 [4. 6. 8.]]

[[[1 2]
  [2 4]]

 [[4 8]
  [7 9]]]


In [ ]:
#np.arange and np.reshape
np.arange(1,20,2).reshape(5,2)


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [ ]:
import numpy as np

a1= np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a2.size)
print(a2.shape)
print(a3)
print(a2)


12
(3, 4)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
# ndim(number of dimmensions)
a1.ndim

1

# Array Operations


In [ ]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Scalar Operations
# Arithmetic
print(a1**2)

print(a1*2)

print(a2+3)

# realtions (this return true or false if the given condition is true or false: >, < , ==, >=, <=)
a2==15


[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# Vector Operations
# arithetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions


In [ ]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[20., 31., 47.],
       [ 8., 23.,  0.],
       [75., 15., 10.]])

In [ ]:
# max/min/sum/prod
# axis=  0-> column & 1-> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))


84.0
8.0
434.0
165090060430848.0


In [ ]:
# mean/median/standard variance(std)/variance(var)
print(np.mean(a1,axis=0))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

[34.33333333 23.         19.        ]
20.0
21.82308212833941
476.24691358024694


# Indexing and Slicing


In [ ]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a2[1,0]

4

In [ ]:
a3[:,:,0]

array([[0, 2],
       [4, 6]])

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
#print(a1)
print(np.dot(a1,a2))
#print(np.add(a1,a2))


[[114 120 126]
 [378 400 422]
 [642 680 718]]


# Numpy Excersise

In [ ]:
import numpy as np
# create an array of 10 zeros
print(np.zeros(10))
# create an array of 10 ones
print(np.ones(10))
# create an array of 10 fives
print(np.ones(10)*5)
# create an array of integers from 10 to 50
print(np.arange(10,51))
# create a n array of all even integers from 10 to 50
print(np.arange(10,51,2))
#create a 3x3 matrix with values ranging from 0 to 8
print(np.arange(9).reshape(3,3))
#create a 3x3 identity matrix
print(np.identity(3))
# use numpy to generate a random numbers between 0 and 1
print(np.random.rand(1))
# use numpy to generate an array of 35 random numbers sampled from a standard distribution
print(np.random.randint(25))
print()
# draw the mattrix with 10x10 space #or :  np.arange(0.01, 1.01, 0.01).reshape(10, 10)
# or: np.arange(1,101).reshape(10,10) /100
print(np.linspace(0.01,1.00,100).reshape(10,10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.55758221]
6

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat= np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#print 20
mat[3,-1]

20

In [ ]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# sum of all the values in mat
print(np.sum(mat))
# standard deviation in mat
print(np.std(mat))
#sum of all the columns in mat
print((np.sum(mat,axis=0)))

325
7.211102550927978
[55 60 65 70 75]
