<a href="https://colab.research.google.com/github/KAyush16/PyLibra/blob/main/numpy_questions150.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr%2!=0])

[1 3 5 7 9]


In [ ]:
# Replace all odd numbers in arr with -1
arr[arr%2!=0]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1 = arr.copy()
arr1[arr1%2!=0]=-1
print(arr1)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
print(np.arange(10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#Stack arrays a and b vertically and horizontally
import numpy as np

a = np.arange(10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)

# Method 1: Corrected np.vstack usage
result_vstack = np.vstack((a, b))
result_hstack = np.hstack((a,b))
print(result_vstack)
print()
print(result_hstack)
print()
# Method 2:
result_concat = np.concatenate([a, b], axis=0) # to do horizontally: axis=1
print(result_concat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# a = np.array([1,2,3])
# pattern : > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

import numpy as np

a = np.array([1, 2, 3])

# Step 1: Repeat each element of 'a' three times
repeated = np.repeat(a, 3)

# Step 2: Tile the original array 'a' three times
tiled = np.tile(a, 3)

# Step 3: Concatenate the two arrays to form the final pattern
pattern = np.concatenate((repeated, tiled))

print(pattern)



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [ ]:
# from binascii import b2a_hqx
# Get the common items between a and b : (.intersect1d)
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_elements = np.intersect1d(a,b)
print(common_elements)

[2 4]


In [ ]:
# "From array a remove all items present in array b"
# numpy.setdiff1d() : function find the set difference of two arrays and return the unique values in arr1 that are not in arr2.
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
remove_items = np.setdiff1d(a,b)
print(remove_items)


In [ ]:
# Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

 How to make a python function that handles scalars to work on numpy arrays?

In [ ]:
# Convert the function maxx that works on two scalars, to work on two arrays.
'''
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
'''
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def pair_max(a, b):
    result = []
    for i, j in zip(a, b): #zip(a, b): This function pairs corresponding elements from a and b.
        if i > j:
            result.append(i)
        else:
            result.append(j)
    return np.array(result)

output = pair_max(a, b)
output

array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
# swaping rows and columns
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(arr[:,[1,0,2]]) # swapping column
print()
print(arr[[0,2,1],:]) # swapping row

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]

[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [ ]:
#  Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
import numpy as np
np.random.uniform(5,10,(5,3))

array([[9.04101579, 9.69555694, 6.30631527],
       [6.98160414, 5.5233137 , 8.40909309],
       [6.41841594, 6.37306058, 5.53424599],
       [9.55687066, 7.24607663, 8.48318979],
       [6.06032589, 8.52127609, 7.9127903 ]])

 How to limit the number of items printed in output of numpy array?

 > To limit the number of items printed in a NumPy array, you can use the "np.set_printoptions" function.

In [ ]:
#  Limit the number of items printed in python numpy array a to a maximum of 6 elements.
# i/p : array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
# o/p : array([ 0,  1,  2, ..., 12, 13, 14])
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# Importing a dataset with numbers and texts keeping the text intact in python numpy

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')